name: 'Pipeline build and push in ECR'

on:
  workflow_call:
    inputs:
      TAG_IMAGE:
        required: true
        type: string
      ECR_REGISTRY:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string

jobs:
  build-push-ecr-develop:
    name: sre-core-banking-templates build and push in ECR
    runs-on: poc-runner
    # env:
    #   TAG_IMAGE: $(echo $GITHUB_SHA | head -c 7)
    #   ECR_REGISTRY: 160927522959.dkr.ecr.us-east-2.amazonaws.com
    #   ECR_REPOSITORY: poc/andersonsilvadocktech
    steps:
    - name: check out code
      uses: actions/checkout@v2

    - name: aws login ecr 
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{inputs.ECR_REGISTRY}}

    - name: Build container image
      run: |
        docker build -t ${{inputs.ECR_REPOSITORY}} .
        docker tag ${{inputs.ECR_REPOSITORY}}:latest ${{inputs.ECR_REGISTRY}}/${{inputs.ECR_REPOSITORY}}:${{inputs.TAG_IMAGE}}

    - name: Push image to ECR
      run: | 
        docker push ${{inputs.ECR_REGISTRY}}/${{inputs.ECR_REPOSITORY}}:${{inputs.TAG_IMAGE}}
